on: [push]

jobs:
  run_it:
    runs-on: ubuntu-latest
    name: Just runs setup-z3
    steps:
    - name: Check out code
      uses: actions/checkout@v1
    - name: Setup Z3
      uses: ./
    - name: Print contents of Z3 directory
      run: "ls `echo $PATH | cut -d: -f1`"
    - name: Test that Z3 is in the path
      run: echo '(assert true) (check-sat)' | z3 -smt2 -in
